# General settings
title: SocioLogs
title_html: "<b>socio</b>logs"
pitch: sociologie, numérique et statistiques
description: >
  Intéressé·e par les liens entre société et numérique ?
  SocioLogs aussi. Des débats théoriques aux questions pratiques, ce blog
  interroge le numérique en croisant sociologie et statistiques.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sociologs.com/" # the base hostname & protocol for your site, e.g. http://example.com

cc: by-nc
dateformat: "%e %B %Y" 
nb_posts_page: 10
repo: https://github.com/gaalcaras/sociologs

# Author
author: Gabriel Alcaras
shortbio: Doctorant en sociologie.
author_display: true

email: gabriel.alcaras@ehess.fr
twitter_username: gaalcaras
github_username: gaalcaras
keybase_username: gaalcaras
linkedin_username: gaalcaras
author_website: https://gaalcaras.com

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks", "autolink", "footnotes"]
theme: academic
gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - jekyll_build.sh
  - Gemfile
  - Gemfile.lock
